### ISSUE TITLE
Optimize GIF Quality Settings in the Interface

### ISSUE THREAD

**Issue by Memory420** [Memory420/GifConverter#1]
### Improving the GIF Quality Control Interface

**Goal**: Enhance control over the quality of generated GIFs.

### Context
The section of the interface with three sliders—resolution, frame rate (fps), and number of colors—requires updates to provide better control over the quality of the final GIF. A new function should be implemented to create a color palette with a limited number of shades, which will be used for GIF conversion.

### Tasks
- [ ] Update the interface for the sliders (resolution, fps, number of colors).
- [ ] Implement a function to generate a color palette with a limited number of colors.
- [ ] Integrate the palette into the GIF conversion process.

### Example
```java
import java.io.IOException;
import java.util.Arrays;

public class GifConverter {

    public static void main(String[] args) {
        // Paths to input video, palette, and output GIF
        String inputVideo = "input.mp4";
        String paletteFile = "palette.png";
        String outputGif = "output.gif";

        try {
            // Step 1: Generate the palette
            ProcessBuilder paletteProcess = new ProcessBuilder(
                "ffmpeg",
                "-i", inputVideo,
                "-vf", "fps=10,scale=360:-2:flags=lanczos,palettegen=max_colors=64",
                paletteFile
            );
            executeProcess(paletteProcess, "Palette generation failed");

            // Step 2: Create the GIF using the generated palette
            ProcessBuilder gifProcess = new ProcessBuilder(
                "ffmpeg",
                "-i", inputVideo,
                "-i", paletteFile,
                "-filter_complex", "fps=10,scale=360:-2:flags=lanczos[x];[x][1:v]paletteuse",
                outputGif
            );
            executeProcess(gifProcess, "GIF creation failed");

            System.out.println("GIF successfully created: " + outputGif);

        } catch (IOException | InterruptedException e) {
            e.printStackTrace();
        }
    }

    private static void executeProcess(ProcessBuilder processBuilder, String errorMessage)
            throws IOException, InterruptedException {
        Process process = processBuilder.inheritIO().start();
        if (process.waitFor() != 0) {
            throw new RuntimeException(errorMessage);
        }
    }
}

**Comment by FriedCerebrum** [comment]
Assign me
